== Vault Workshop

=== Setup Infrastructure

Start consul
[source,shell]
----
$ TODO
----

Start vault

[source,shell]
----
$ vault server -config=config.hcl
----
Error initializing core: Failed to lock memory: cannot allocate memory

Solution :
[source,shell]
----
$ sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))
----
Again
[source,shell]
----
$ vault server -config=config.hcl
----

[source,shell]
----
$ export VAULT_ADDR=http://127.0.0.1:8200  
$ export VAULT_SKIP_VERIFY=1
----

[source,shell]
----
$ vault operator init \
      -recovery-shares=1 \
      -recovery-threshold=1 \
      -recovery-pgp-keys="keybase:yakhyadabo"
      -root-token-pgp-key="keybase:yakhyadabo"
----

[source,shell]
----
vault operator unseal
----

=== Vault pki

1. Enable pki
[source,shell]
----
$ vault secrets enable pki
----

Tune the pki secrets engine to issue certificates with a maximum time-to-live (TTL) of 87600 hours
[source,shell]
----
$ vault secrets tune -max-lease-ttl=87600h pki
----

2. Generate Root CA

[source,shell]
----
vault write -format=json pki/root/generate/internal \
 common_name="example.com" ttl=87600h | tee \
>(jq -r .data.certificate > ca.pem) \
>(jq -r .data.issuing_ca > issuing_ca.pem) \
>(jq -r .data.private_key > ca-key.pem)
----

This generates a new self-signed CA certificate and private key. Vault will automatically revoke the generated root at the end of its lease period (TTL); the CA certificate will sign its own Certificate Revocation List (CRL).


Check from the API itself
[source,shell]
----
curl -s http://localhost:8200/v1/pki/ca/pem | openssl x509 -text 
----

Configure the CA and CRL URLs
[source,shell]
----
$ vault write pki/config/urls \
        issuing_certificates="http://127.0.0.1:8200/v1/pki/ca" \
        crl_distribution_points="http://127.0.0.1:8200/v1/pki/crl"
----

3. Generate Intermediate CA

[source,shell]
----
$ vault secrets enable -path=pki_int pki
$ vault secrets tune -max-lease-ttl=43800h pki_int
----

Generate an intermediate and save the CSR as pki_intermediate.csr

[source,shell]
----
vault write -format=json pki_int/intermediate/generate/internal \
common_name="example.com Intermediate Authority" ttl=43800h | tee \
>(jq -r .data.csr > pki_intermediate.csr) \
>(jq -r .data.private_key > pki_intermediate.pem)
----


Sign the intermediate certificate with the root certificate and save the generated certificate as intermediate.cert.pem
(Setting up our Intermediate CA require signing our CSR using our Root CA)

[source,shell]
----
vault write -format=json pki/root/sign-intermediate \
csr=@pki_intermediate.csr \
common_name="example.com Intermediate Authority" ttl=43800h | tee \
>(jq -r .data.certificate > pki_intermediate.cert.pem) \
>(jq -r .data.issuing_ca > pki_intermediate_issuing_ca.pem)
----

Once the CSR is signed and the root CA returns a certificate, it can be imported back into Vault:

[source,shell]
----
vault write pki_int/intermediate/set-signed certificate=@pki_intermediate.cert.pem
----

Create Pki Role

[source,shell]
----
$ vault write pki_int/roles/example-dot-com \
        allowed_domains="example.com" \
        allow_subdomains=true \
        max_ttl="720h"
----

CRL configuration
[source,shell]
----
$ vault write pki_int/config/urls issuing_certificates="http://127.0.0.1:8200/v1/pki_int/ca" crl_distribution_points="http://127.0.0.1:8200/v1/pki_int/crl"
----

Issue a certificate
[source,shell]
----
vault write pki_int/issue/example-dot-com common_name="test.example.com" ttl="24h"
----

Allow clients to generate their own certificates
[source,shell]
----
$ vault policy write pki_int policy/pki_int.hcl
----

https://learn.hashicorp.com/vault/secrets-management/sm-pki-engine
http://yet.org/2018/10/vault-pki/

