version: '3'

services:

    vault:
      image: vault:latest
      volumes:
        - ./config:/vault/config
        - ./policies:/vault/policies
        - ./data:/vault/data:z
      ports:
        - 8200:8200
      environment:
        - SKIP_SETCAP=true
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
      cap_add:
        - IPC_LOCK
      command: vault server -config=/vault/config/config.hcl

      network_mode: "host"